### ISSUE TITLE
skipped test are failing the test run

### ISSUE THREAD

**Issue by chuym** [mixmaxhq/erik#9]
Not sure if this is Erik's scope or Karma itself?

Skipped tests are causing Erik to exit with failure status:

```
  PublicationModel
    #set
      ✔ should triger "change" for any change (skipped)

Finished in 0.003 secs / 0 secs @ 11:52:39 GMT-0700 (MST)

SUMMARY:
✔ 0 tests completed
ℹ 1 test skipped
[11:52:39] 'erik-run-spec' errored after 1.5 s
[11:52:39] Error: Karma returned with the exit code: 1
    at /Users/chuy/work/shared_modules/backbone-publication/node_modules/erik/index.js:150:19
    at removeAllListeners (/Users/chuy/work/shared_modules/backbone-publication/node_modules/erik/node_modules/karma/lib/server.js:380:7)
    at Server.<anonymous> (/Users/chuy/work/shared_modules/backbone-publication/node_modules/erik/node_modules/karma/lib/server.js:391:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1553:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This is the test suite used:

```
describe('PublicationModel', () => {
  describe('#set', () => {
    it('should triger "change" for a set in object style');
  });
});
```

If I implement the test and have it pass, Erik exits successfully,

Expected: Skipped tests should not cause a failure.

**Comment by spencer-brown** [comment]
looks like setting `failOnEmptyTestSuite` to false (documented [here](http://karma-runner.github.io/1.0/config/configuration-file.html)) might be the fix for this.
